### PR TITLE
Add Couchbase + K8s

### PR DESCRIPTION
**Pull request by simone98dm**

### CODE REVIEW

**Comment by simone98dm** [comment]
Looking at the preview, the title is too long for the view, so I was wondering if reducing the title from: "NoSQL + K8s: secure production-ready in less than 10 minutes" to "Couchbase + Kubernetes" could be better🧐, what do you think?

**Comment by cortinico** [comment]
> Looking at the preview, the title is too long for the view, so I was wondering if reducing the title from: "NoSQL + K8s: secure production-ready in less than 10 minutes" to "Couchbase + Kubernetes" could be better🧐, what do you think?

Thanks for sending this over. I'm trying to stick to conferences only, as I don't have capacity to track all the meetups as well. This looks more like a meetup right?

**Comment by simone98dm** [comment]
Yes, this could be more similar to a meetup. So, can I suggest creating a `CONTRIBUTING` file with a list of tips? Could be helpful for future contributions

**Comment by cortinico** [comment]
> Yes, this could be more similar to a meetup. So, can I suggest creating a `CONTRIBUTING` file with a list of tips? Could be helpful for future contributions

Yeah totally 👍 Closing this and looking forward to that `CONTRIBUTING` file if you wish :)

**Pull request closed without merging**
